#!name=TIDALHiFiPlusCrack
#!desc=TIDALHiFiPlusCrack

[MITM]

hostname = %APPEND% api.tidal.com

[Script]

# > TIDAL解锁HiFi Plus
TIDALHiFiPlusCrack = type=http-response, pattern=^https?:\/\/api\.tidal\.com\/v1\/users\/\d+\/subscription.+, script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/TIDALHiFiPlusCrack.js, requires-body=true, max-size=-1, timeout=60

TidalHiFiPlusCrack = type=http-request, pattern=^https?:\/\/api\.tidal\.com\/v1\/tracks/\d+\/playbackinfopostpaywall.+, script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/TidalHiFiPlusCrack.js, requires-body=true, max-size=-1, timeout=60

